import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, Computed, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import ENUM, TSTZRANGE, UUID, ExcludeConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.models.base import UUIDPKMixin, TimestampMixin

appointment_status_enum = ENUM(
    "PENDING", "CONFIRMED", "CHECKED_IN", "COMPLETED",
    "CANCELLED", "RESCHEDULED", "NO_SHOW", "EXPIRED",
    name="appointment_status", create_type=False,
)


class Appointment(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "appointments"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE")
    )
    service_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="SET NULL")
    )
    customer_name: Mapped[str] = mapped_column(String(150))
    customer_phone: Mapped[str] = mapped_column(String(20))
    customer_email: Mapped[str | None] = mapped_column(String(255))
    # Verified phone number shared by a Telegram customer via the bot's
    # native "request contact" button (see app/services/whatsapp_bot.py's
    # AWAIT_CONTACT step). Deliberately a separate, nullable column rather
    # than reusing `customer_phone`: for Telegram, `customer_phone` still
    # holds the chat id, exactly as before, because the "look up/cancel my
    # booking" flow scopes results with
    # `Appointment.customer_phone == session.customer_phone` (chat id for
    # Telegram, real phone for WhatsApp) — overwriting it would silently
    # break that lookup. This column is purely additive: NULL for every
    # WhatsApp booking and for any Telegram booking made before this field
    # existed, and never read by the WhatsApp flow, the public API, or the
    # admin dashboard.
    telegram_contact_phone: Mapped[str | None] = mapped_column(String(20))
    scheduled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    duration_minutes: Mapped[int] = mapped_column(Integer)

    # Mirrors: GENERATED ALWAYS AS (appointment_tstzrange(scheduled_at, duration_minutes)) STORED
    # Computed() tells SQLAlchemy this is server-generated — never set it from Python,
    # the DB computes and stores it on every insert/update.
    appointment_range: Mapped[str] = mapped_column(
        TSTZRANGE,
        Computed(
            "appointment_tstzrange(scheduled_at, duration_minutes)", persisted=True
        ),
    )

    status: Mapped[str] = mapped_column(appointment_status_enum, default="PENDING")
    notes: Mapped[str | None] = mapped_column(Text)
    reminder_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    booking_ref: Mapped[str] = mapped_column(String(20), unique=True)

    __table_args__ = (
        CheckConstraint("duration_minutes > 0", name="chk_appt_duration_positive"),
        CheckConstraint(
            r"customer_phone ~ '^\+?[0-9]{7,15}$'", name="chk_appt_phone_format"
        ),
        CheckConstraint(
            r"telegram_contact_phone IS NULL OR telegram_contact_phone ~ '^\+?[0-9]{7,15}$'",
            name="chk_appt_telegram_contact_phone_format",
        ),
        # Declared here so Alembic's autogenerate recognizes it as already present
        # (it was created by 001_init_schema.sql, not by this ORM layer) rather
        # than proposing to add a duplicate on the next `alembic revision --autogenerate`.
        ExcludeConstraint(
            (text("tenant_id"), "="),
            (text("appointment_range"), "&&"),
            name="excl_appointments_no_overlap",
            using="gist",
            where=text("status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN')"),
        ),
    )


class AvailableSlot(UUIDPKMixin, Base):
    """Computed cache table — regenerated by the nightly slot-generation job.
    Safe to truncate and rebuild; never a source of truth on its own."""

    __tablename__ = "available_slots"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE")
    )
    service_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="CASCADE")
    )
    slot_datetime: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    duration_minutes: Mapped[int] = mapped_column(Integer)
    booked: Mapped[bool] = mapped_column(default=False)
    blocked: Mapped[bool] = mapped_column(default=False)
    reason: Mapped[str | None] = mapped_column(String(255))
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        # Lets the nightly job UPSERT (ON CONFLICT (tenant_id, service_id, slot_datetime))
        # instead of duplicating rows on each regeneration run.
        UniqueConstraint(
            "tenant_id", "service_id", "slot_datetime",
            name="uq_available_slots_identity",
        ),
    )
